spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: dbswetlox
  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB